---
services:
  ser2net:
    image: gringolito/ser2net:latest
    container_name: ser2net
    networks:
      home-network:
        ipv4_address: ${SER2NET_PUBLIC_IP_ADDRESS}
    environment:
      - SER2NET_CONFIGPATH=/ser2net
    volumes:
      - ser2net_config:/ser2net
    devices:
      - ${SER2NET_SERIAL_DEVICE}
    restart: unless-stopped

volumes:
  ser2net_config:

networks:
  home-network:
    external: true
