---
services:
  ser2net:
    image: gringolito/ser2net:${SER2NET_TAG:-latest}
    container_name: ser2net
    environment:
      - SER2NET_CONFIGPATH=/ser2net
    volumes:
      - ser2net_config:/ser2net
    devices:
      - ${SER2NET_SERIAL_DEVICE}
    ports:
      - ${SER2NET_9600_PORT:-4000}:4000
      - ${SER2NET_57600_PORT:-4001}:4001
      - ${SER2NET_115200_PORT:-4002}:4002
      - ${SER2NET_1500000_PORT:-4003}:4003
      - ${SER2NET_ADMIN_PORT:-9999}:9999
    restart: unless-stopped

volumes:
  ser2net_config:
