---
name: grist

services:
  jellyfin:
    image: gristlabs/grist:${GRIST_TAG:-latest}
    container_name: grist
    user: ${GRIST_UID:-1000}:${GRIST_GID:-1000}
    environment:
      - TZ=${GRIST_TZ:-America/Sao_Paulo}
      - GRIST_SESSION_SECRET=${GRIST_SESSION_SECRET}
      - GRIST_DEFAULT_EMAIL=${GRIST_EMAIL}
      - GRIST_SANDBOX_FLAVOR=${GRIST_SANDBOX_FLAVOR:-gvisor}
      - APP_HOME_URL=https://grist.${GRIST_PUBLIC_DOMAIN}
    volumes:
      - persist:/persist
    networks:
      proxy-network:
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.grist.rule: Host(`grist.${GRIST_PUBLIC_DOMAIN}`)
      traefik.http.services.grist.loadbalancer.server.port: 8484

volumes:
  persist:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,sync,nfsvers=4
      device: :${NFS_GRIST_PERSIST_SHARE}

networks:
  proxy-network:
    external: true
