---
services:
  server:
    image: docker.gitea.com/gitea:${GITEA_TAG:-latest}-rootless
    container_name: gitea
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    pids_limit: 512
    user: ${GITEA_USERID:-1000}:${GITEA_GROUPID:-1000}
    environment:
      - TZ=${GITEA_TZ:-America/Sao_Paulo}
    restart: always
    networks:
      proxy-network:
    ports:
      - ${GITEA_SSH_PORT:-2222}:2222
    volumes:
      - config:/etc/gitea
      - data:/var/lib/gitea
      - repositories:/git
    labels:
      traefik.enable: true
      traefik.http.routers.gitea.rule: Host(`git.${GITEA_PUBLIC_DOMAIN}`)
      traefik.http.services.gitea.loadbalancer.server.port: 3000

volumes:
  config:
    external: true
    name: ${GITEA_CONFIG_VOLUME}
  data:
    external: true
    name: ${GITEA_DATA_VOLUME}
  repositories:
    external: true
    name: ${GITEA_REPOSITORIES_VOLUME}

networks:
  proxy-network:
    external: true
    name: ${GITEA_NETWORK}
