---
version: "3.8"

services:
  server:
    image: gitea/gitea:1.22
    container_name: gitea
    environment:
      - TZ=America/Sao_Paulo
      - USER_UID=${USERID}
      - USER_GID=${USERID}
      - USER=git
    restart: always
    networks:
      home:
        ipv4_address: ${PUBLIC_IP_ADDRESS}
      proxy-network:
    volumes:
      - data:/data
      - repos:/git
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: true
      traefik.http.routers.gitea.rule: Host(`git.${PUBLIC_DOMAIN}`)
      traefik.http.services.gitea.loadbalancer.server.port: 80

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},rw,sync,nolock"
      device: ":${NFS_GITEA_SHARE}"
  repos:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},rw,sync"
      device: ":${NFS_REPOS_SHARE}"

networks:
  home:
    external: true
    name: home-network
  proxy-network:
    external: true
