---
services:
  server:
    image: gitea/gitea:${GITEA_TAG:-latest}
    container_name: gitea
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${GITEA_TZ:-America/Sao_Paulo}
      - USER_UID=${GITEA_USERID:-1000}
      - USER_GID=${GITEA_GROUPID:-1000}
      - USER=${GITEA_USER:-git}
    restart: always
    networks:
      proxy-network:
    ports:
      - ${GITEA_SSH_PORT:-2222}:22
    volumes:
      - data:/data
      - repositories:/git
    labels:
      traefik.enable: true
      traefik.http.routers.gitea.rule: Host(`git.${GITEA_PUBLIC_DOMAIN}`)
      traefik.http.services.gitea.loadbalancer.server.port: 80

volumes:
  data:
    external: true
    name: ${GITEA_DATA_VOLUME}
  repositories:
    external: true
    name: ${GITEA_REPOSITORIES_VOLUME}

networks:
  proxy-network:
    external: true
    name: ${GITEA_NETWORK}
