---
services:
  server:
    image: gitea/gitea:${GITEA_TAG:-latest}
    container_name: gitea
    environment:
      - TZ=${GITEA_TZ:-America/Sao_Paulo}
      - USER_UID=${GITEA_USERID}
      - USER_GID=${GITEA_USERID}
      - USER=${GITEA_USER:-git}
    restart: always
    networks:
      proxy-network:
    ports:
      - ${GITEA_SSH_PORT:-2222}:22
    volumes:
      - data:/data
      - repos:/git
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: true
      traefik.http.routers.gitea.rule: Host(`git.${GITEA_PUBLIC_DOMAIN}`)
      traefik.http.services.gitea.loadbalancer.server.port: 80

volumes:
  data:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,sync,nfsvers=4
      device: :${NFS_GITEA_SHARE}
  repos:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,sync,nfsvers=4
      device: :${NFS_REPOS_SHARE}

networks:
  proxy-network:
    external: true
