---
services:
  traefik:
    image: traefik:${TRAEFIK_TAG:-latest}
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy-network:
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --global.checknewversion
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http3
      - --log.level=${TRAEFIK_LOG_LEVEL:-INFO}
      - --tracing=${TRAEFIK_TRACING:-false}
      - --accesslog=${TRAEFIK_ACCESS_LOGS:-false}
      - --accesslog.otlp=${TRAEFIK_ACCESS_LOG_OLTP:-false}
    environment:
      - TZ=${TRAEFIK_TZ:-America/Sao_Paulo}

networks:
  proxy-network:
    external: true
