---
services:
  traefik:
    image: traefik:${TRAEFIK_TAG:-latest}
    container_name: traefik
    restart: unless-stopped
    user: ${TRAEFIK_USERID:-1000}:${TRAEFIK_GROUPID:-1000}
    group_add:
      - ${TRAEFIK_DOCKER_GROUPID:-985}
    cap_add:
      - CAP_NET_BIND_SERVICE
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    pids_limit: 512
    networks:
      - proxy-network
    ports:
      - ${TRAEFIK_HTTP_PORT:-80}:80
      - ${TRAEFIK_HTTPS_PORT:-443}:443
      - ${TRAEFIK_API_PORT:-8080}:8080
    volumes:
      - ${TRAEFIK_DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock:ro,z
    environment:
      - TZ=${TRAEFIK_TZ:-America/Sao_Paulo}
      - LEGO_DISABLE_CNAME_SUPPORT=true
    command:
      - --global.checknewversion
      - --api.insecure=${TRAEFIK_API_INSECURE:-true}
      - --api.dashboard=${TRAEFIK_API_DASHBOARD:-true}
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --serverstransport.insecureskipverify
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http3
      - --log.level=${TRAEFIK_LOG_LEVEL:-INFO}
      - --tracing=${TRAEFIK_TRACING:-false}
      - --accesslog=${TRAEFIK_ACCESS_LOGS:-false}
      - --accesslog.otlp=${TRAEFIK_ACCESS_LOG_OLTP:-false}

networks:
  proxy-network:
    external: true
    name: ${TRAEFIK_NETWORK}
