---
name: stremio-jackett

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${FLARESOLVERR_LOG_LEVEL:-info}
      - LOG_HTML=${FLARESOLVERR_LOG_HTML:-false}
      - CAPTCHA_SOLVER=${FLARESOLVERR_CAPTCHA_SOLVER:-none}
      - PUID=${STREMIO_JACKETT_UID:-1000}
      - PGID=${STREMIO_JACKETT_GID:-1000}
      - TZ=${STREMIO_JACKETT_TZ:-America/Sao_Paulo}
    networks:
      proxy-network:
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${STREMIO_JACKETT_UID:-1000}
      - PGID=${STREMIO_JACKETT_GID:-1000}
      - TZ=${STREMIO_JACKETT_TZ:-America/Sao_Paulo}
      - AUTO_UPDATE=true
    depends_on:
      - flaresolverr
    networks:
      proxy-network:
    volumes:
      - jackett-config:/config
      - jackett-data:/downloads
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.jackett.rule: Host(`jackett.${STREMIO_JACKETT_PUBLIC_DOMAIN}`)
      traefik.http.services.jackett.loadbalancer.server.port: 9117

  jackett-stremio:
    image: belmeg/stremio-addon-jackett
    container_name: jackett-stremio
    environment:
      - PUID=${STREMIO_JACKETT_UID:-1000}
      - PGID=${STREMIO_JACKETT_GID:-1000}
      - TZ=${STREMIO_JACKETT_TZ:-America/Sao_Paulo}
      - ADDON_NAME=stremio-jacket
    depends_on:
      - jackett
    networks:
      proxy-network:
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.stremio-jackett.rule: Host(`stremio-jackett.${STREMIO_JACKETT_PUBLIC_DOMAIN}`)
      traefik.http.services.stremio-jackett.loadbalancer.server.port: 3000

networks:
  proxy-network:
    external: true

volumes:
  jackett-config:
    driver_opts:
      type: nfs
      o: addr=${STREMIO_JACKETT_NFS_SERVER},rw,sync,nfsvers=4
      device: :${JACKETT_CONFIG_NFS_SHARE}

  jackett-data:
    driver_opts:
      type: nfs
      o: addr=${STREMIO_JACKETT_NFS_SERVER},rw,sync,nfsvers=4
      device: :${JACKETT_DATA_NFS_SHARE}
