---
name: zabbix-agent

services:
  zabbix-agent:
    image: zabbix/zabbix-agent2:${ZABBIX_AGENT_TAG:-ol-7.0-latest}
    container_name: zabbix-agent
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    group_add:
      - ${DOCKER_GROUPID:-985}
    environment:
      TZ: ${ZABBIX_AGENT_TZ:-America/Sao_Paulo}
      ZBX_SERVER_HOST: ${ZABBIX_SERVER_HOST}
      ZBX_HOSTNAME: ${ZABBIX_AGENT_HOSTNAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
    read_only: true
    network_mode: host
    pid: host
    restart: unless-stopped
