---
name: checkmk
services:
  checkmk:
    image: checkmk/check-mk-raw:${CHECKMK_TAG:-latest}
    container_name: checkmk
    environment:
      TZ: ${CHECKMK_TZ:-America/Sao_Paulo}
      CMK_PASSWORD: ${CHECKMK_PASSWORD}
    # tmpfs: /opt/omd/sites/cmk/tmp:uid=${CHECKMK_UID:-1000},gid=${CHECKMK_GID:-1000}
    volumes:
      - monitoring:/omd/sites
    ports:
      - 8000:8000 # Checkmk Agent Receiver
    networks:
      proxy-network:
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.checkmk.rule: Host(`checkmk.${CHECKMK_PUBLIC_DOMAIN}`)
      traefik.http.services.checkmk.loadbalancer.server.port: 5000

volumes:
  monitoring:
    external: true
    name: ${CHECKMK_MONITORING_VOLUME}

networks:
  proxy-network:
    external: true
