---
name: jellyfin

services:
  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_TAG:-latest}
    container_name: jellyfin
    user: ${JELLYFIN_UID:-1000}:${JELLYFIN_GID:-1000}
    environment:
      - TZ=${JELLYFIN_TZ:-America/Sao_Paulo}
      - JELLYFIN_PublishedServerUrl=https://jellyfin.${JELLYFIN_PUBLIC_DOMAIN}
    volumes:
      - config:/config
      - cache:/cache
      - media:/media
    ports:
      - 7359:7359 # local discovery
      - 1900:1900 # service discovery (DLNA)
    networks:
      proxy-network:
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.${JELLYFIN_PUBLIC_DOMAIN}`)
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096

volumes:
  media:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,sync,nfsvers=4
      device: :${NFS_JELLYFIN_MEDIA_SHARE}
  config:
  cache:

networks:
  proxy-network:
    external: true
