---
name: beszel

services:
  beszel:
    image: henrygd/beszel:${BESZEL_TAG:-latest}
    container_name: beszel
    environment:
      TZ: ${BESZEL_TZ:-America/Sao_Paulo}
    user: ${BESZEL_UID:-1000}:${BESZEL_GID:-1000}
    # ports:
    #   - 8090:8090
    volumes:
      - beszel-data:/beszel_data
    networks:
      proxy-network:
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.beszel.rule: Host(`beszel.${BESZEL_PUBLIC_DOMAIN}`)
      traefik.http.services.beszel.loadbalancer.server.port: 8090

  beszel-agent:
    image: henrygd/beszel-agent:${BESZEL_AGENT_TAG:-latest}
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - beszel-agent:/var/lib/beszel-agent
    environment:
      LISTEN: 45876
      HUB_URL: https://beszel.${BESZEL_PUBLIC_DOMAIN}
      TOKEN: ${BESZEL_API_TOKEN}
      KEY: ${BESZEL_PUBLIC_KEY}

volumes:
  beszel-data:
    external: true
    name: ${BESZEL_DATA_VOLUME}
  beszel-agent:
    external: true
    name: ${BESZEL_AGENT_VOLUME}

networks:
  proxy-network:
    external: true
