---
name: beszel

services:
  hub:
    image: henrygd/beszel:${BESZEL_TAG:-latest}
    container_name: beszel
    environment:
      TZ: ${BESZEL_TZ:-America/Sao_Paulo}
    user: ${BESZEL_UID:-1000}:${BESZEL_GID:-1000}
    volumes:
      - beszel-data:/beszel_data
    networks:
      proxy-network:
    restart: unless-stopped
    healthcheck:
      test: ['CMD', '/beszel', 'health', '--url', 'http://localhost:8090']
      start_period: 5s
      interval: 60s
    labels:
      traefik.enable: true
      traefik.http.routers.beszel.rule: Host(`beszel.${BESZEL_PUBLIC_DOMAIN}`)
      traefik.http.services.beszel.loadbalancer.server.port: 8090

  agent:
    image: henrygd/beszel-agent:${BESZEL_AGENT_TAG:-latest}
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - beszel-agent:/var/lib/beszel-agent
    environment:
      LISTEN: 45876
      HUB_URL: https://beszel.${BESZEL_PUBLIC_DOMAIN}
      TOKEN: ${BESZEL_API_TOKEN}
      KEY: ${BESZEL_PUBLIC_KEY}
    healthcheck:
      test: ['CMD', '/agent', 'health']
      interval: 60s

volumes:
  beszel-data:
    external: true
    name: ${BESZEL_DATA_VOLUME}
  beszel-agent:
    external: true
    name: ${BESZEL_AGENT_VOLUME}

networks:
  proxy-network:
    external: true
