---
services:
  qbittorrent:
    image: wernight/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    volumes:
      - config:/config
      - torrents:/torrents
      - downloads:/downloads
    networks:
      proxy-network:
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.rule: Host(`torrent.${PUBLIC_DOMAIN}`)
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080

volumes:
  config:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,sync
      device: :${NFS_QBITTORRENT_CONFIG_SHARE}
  torrents:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,sync
      device: :${NFS_TORRENTS_SHARE}
  downloads:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,sync
      device: :${NFS_DOWNLOADS_SHARE}

networks:
  proxy-network:
    external: true
